package net.crunchycodes.bouncer.live.wallpaper

import org.junit.Test

import org.junit.Assert.*

/**
 * Placeholder host-side test generated by the Android template.
 *
 * See [testing documentation](http://d.android.com/tools/testing).
 */
class ExampleUnitTest {
    @Test
    fun addition_isCorrect() {
        assertEquals(4, 2 + 2)
    }
}
